#!/bin/sh -e

# Make sure gmp is built with generic options.
cp -v gcc/gmp/configfsf.guess gcc/gmp/config.guess
cp -v gcc/gmp/configfsf.sub   gcc/gmp/config.sub

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

export libat_cv_have_ifunc=no

../gcc/configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-multilib \
    --disable-symvers \
    --disable-libmpx \
    --disable-libmudflap \
    --disable-libsanitizer \
    --disable-werror \
    --disable-fixed-point \
    --disable-libstdcxx-pch \
    --enable-checking=release \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --with-system-zlib \
    --enable-__cxa_atexit \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-languages=c,c++ \
    --build=armv7-linux-musleabihf \
    --without-included-gettext \
    --disable-libssp \
    --with-float=hard \
    --disable-bootstrap

make
make DESTDIR="$1" install

# Save 35MB.
find "$1" -name libgtkpeer.a  -delete
find "$1" -name libgjsmalsa.a -delete
find "$1" -name libgij.a      -delete

# Some legacy programs will expect cc
ln -s gcc "$1/usr/bin/cc"

# POSIX compliance.
install -Dm755 ../c99 "$1/usr/bin/c99"

# Symlink for LTO.
{
    mkdir -p "$1/usr/lib/bfd-plugins"

    ln -s /usr/libexec/gcc/armv7-linux-musleabihf/10.1.0/liblto_plugin.so \
          "$1/usr/lib/bfd-plugins/liblto_plugin.so"
}
